WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Models/Productos.cs
namespace WebApplication1.Models
{
    public class Productos
    {
        public int Productos_Id { get; set; }
        public string NombreArticulo { get; set; }
        public string Color { get; set; }
        public string Descripcion { get; set; }
    }
}

WebApplication1/Models/Usuario.cs
namespace WebApplication1.Models
{
    public class Usuario
    {
        public string Nombre { get; set; }
        public string Correo { get; set; }
        public string Clave { get; set; }

        public string[] Roles { get; set; }
    }
}

WebApplication1/Controllers/AccesoController.cs
using Microsoft.AspNetCore.Mvc;

using WebApplication1.Models;
using WebApplication1.Data;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using System.Security.Claims;

namespace WebApplication1.Controllers
{
    public class AccesoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        //USAR REFERENCIAS Models y Data
        [HttpPost]
        public async Task<IActionResult> Index(Usuario _usuario)
        {
            DA_Usuario _da_usuario = new DA_Usuario();

            var usuario = _da_usuario.ValidarUsuario(_usuario.Correo,_usuario.Clave);

            if (usuario != null)
            {

                //2.- CONFIGURACION DE LA AUTENTICACION
                #region AUTENTICACTION
                var claims = new List<Claim>
                {
                    new Claim(ClaimTypes.Name, usuario.Nombre),
                    new Claim("Correo", usuario.Correo),
                };
                foreach (string rol in usuario.Roles) {
                    claims.Add(new Claim(ClaimTypes.Role, rol));
                }
                var claimsIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimsIdentity));
                #endregion


                return RedirectToAction("Index", "Home");
            }
            else {
                return View();
            }
            
        }

        public async Task<IActionResult> Salir()
        {
            //3.- CONFIGURACION DE LA AUTENTICACION
            #region AUTENTICACTION
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            #endregion

            return RedirectToAction("Index");

        }

    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

//1.- AÑADIR LA AUTORIZACION
using Microsoft.AspNetCore.Authorization;

namespace WebApplication1.Controllers
{
    //2.- AÑADIR LA AUTORIZACION
    //[Authorize]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        public readonly ApplicationDbContext _contexto;
        public HomeController(ApplicationDbContext contexto, ILogger<HomeController> logger)
        {
            _contexto = contexto;
            _logger = logger;
        }

        [Authorize(Roles = "Administrador,Vendedor,Empleado")]
        [HttpGet]
        public IActionResult Index()
        {
            List<Productos> listaProductos = _contexto.Productos.ToList();
            return View(listaProductos);
        }

        [Authorize(Roles = "Administrador,Vendedor")]
        [HttpGet]
        public IActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Crear(Productos producto)
        {
            if (ModelState.IsValid)
            {
                _contexto.Productos.Add(producto);
                _contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        [Authorize(Roles = "Administrador,Vendedor")]
        [HttpGet]
        public IActionResult Editar(int? id)
        {
            if (id == null)
            {
                return View();
            }

            var producto = _contexto.Productos.FirstOrDefault(c => c.Productos_Id == id);
            return View(producto);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Editar(Productos producto)
        {
            if (ModelState.IsValid)
            {
                _contexto.Productos.Update(producto);
                _contexto.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            return View(producto);
        }

        [Authorize(Roles = "Administrador")]
        [HttpGet]
        public IActionResult Borrar(int? id)
        {
            var producto = _contexto.Productos.FirstOrDefault(c => c.Productos_Id == id);
            _contexto.Productos.Remove(producto);
            _contexto.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Views/Acceso/Index.cshtml
@model Usuario
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>

    @*------ GOOGLEAR ====> form bootstrap 5 ----------------*@

    <div class="row mt-5">
        <div class="col-sm-4 offset-sm-4">

         <form asp-controller="Acceso" asp-action="Index" method="post">
              <div class="mb-3">
                <label for="exampleInputEmail1" class="form-label">Email address</label>
                <input type="email" class="form-control" asp-for="Correo">
                @*<div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>*@
              </div>
              <div class="mb-3">
                <label for="exampleInputPassword1" class="form-label">Password</label>
                <input type="password" class="form-control" asp-for="Clave">
              </div>
             @* <div class="mb-3 form-check">
                <input type="checkbox" class="form-check-input" id="exampleCheck1">
                <label class="form-check-label" for="exampleCheck1">Check me out</label>
              </div>*@
              <button type="submit" class="btn btn-primary">Submit</button>
        </form>


        </div>
    </div>

  

</body>
   <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</html>

WebApplication1/Views/Home/Crear.cshtml
@model WebApplication1.Models.Productos
@{
    ViewData["Title"] = "Agregar producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<h3 class="text-center">Agregar producto</h3>
<form method="post" asp-action="Crear">
    <div class="row">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-12 mt-4">
            <div class="row">
                <div class="col-4">
                    <label asp-for="NombreArticulo">Nombre</label>
                </div>
                <div class="col-8">
                    <input asp-for="NombreArticulo" class="form-control" />
                    <span asp-validation-for="NombreArticulo" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    <label asp-for="Color"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>
            </div>
            <div class="row">
                <div class="col-4">
                    <label asp-for="Descripcion">Descripción</label>
                </div>
                <div class="col-8">
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>
            </div>

        </div>
    </div>
    <div class="row mt-4">
        <div class="col-3">
            <a asp-action="Index">Volver atrás</a>
        </div>
        <div class="col-5 offset-4">
            <button type="submit" class="btn btn-primary form-control">Crear</button>
            &nbsp;
        </div>
    </div>
</form>

WebApplication1/Views/Home/Editar.cshtml
@model WebApplication1.Models.Productos
@{
    ViewData["Title"] = "Editar Producto";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />
<h3 class="text-center">Editar Producto</h3>
<form method="post" asp-action="Editar">
    <!--Importante para editar-->
    <input type="hidden" asp-for="Productos_Id" />

    <div class="row">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-12 mt-4">
            <div class="row">
                <div class="col-4">
                    <label asp-for="NombreArticulo"></label>
                </div>
                <div class="col-8">
                    <input asp-for="NombreArticulo" class="form-control" />
                    <span asp-validation-for="NombreArticulo" class="text-danger"></span>
                </div>

                <div class="col-4">
                    <label asp-for="Color"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Color" class="form-control" />
                    <span asp-validation-for="Color" class="text-danger"></span>
                </div>

                <div class="col-4">
                    <label asp-for="Descripcion"></label>
                </div>
                <div class="col-8">
                    <input asp-for="Descripcion" class="form-control" />
                    <span asp-validation-for="Descripcion" class="text-danger"></span>
                </div>

            </div>


        </div>
    </div>
    <div class="row mt-4">
        <div class="col-3">
            <a asp-action="Index">Volver a lista de productos</a>
        </div>
        <div class="col-5 offset-4">
            <button type="submit" class="btn btn-primary form-control">Guardar cambios</button>
            &nbsp;
        </div>
    </div>
</form>

WebApplication1/Views/Home/Index.cshtml
@model IEnumerable<WebApplication1.Models.Productos>
@{
    ViewData["Title"] = "Lista de Productos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row">
    <div class="col-4">
        <h3>Productos</h3>
    </div>
    <div class="col-3">
        <a asp-action="Crear" class="btn btn-primary form-control">Agregar Producto</a>
    </div>
</div>

<div>
    @if (Model.Count() > 0)
    {
        <table class="table table-striped border">
            <tr>
                <th>Nombre</th>
                <th>Color</th>
                <th>Descripción</th>
                <th></th>
            </tr>
            @foreach (var productos in Model)
            {
                <tr>
                    <td>@productos.NombreArticulo</td>
                    <td>@productos.Color</td>
                    <td>@productos.Descripcion</td>
                    <td>
                        @if (User.IsInRole("Administrador"))
                        {
                            <a class="btn btn-primary text-white" asp-action="Editar" asp-route-id="@productos.Productos_Id">Editar</a>
                            <a class="btn btn-danger text-white" asp-action="Borrar" asp-route-id="@productos.Productos_Id">Borrar</a>
                        }
                        @if (User.IsInRole("Vendedor"))
                        {
                            <a class="btn btn-primary text-white" asp-action="Editar" asp-route-id="@productos.Productos_Id">Editar</a>
                        }
                    </td>
                </tr>
            }
        </table>
    }
    else
    {
        <p>No hay artículos</p>
    }
</div>

WebApplication1/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Acceso" asp-action="Salir">Salir</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>